id: P003139
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:42:58.873058
source_metadata:
  id: bdr:W3MS67
  title: དཔལ་ཕྱག་ན་རྡོ་རྗེ་འབྱུང་པོ་འདུལ་བྱེད་ཀྱི་བརྒྱུད་འདེབས་སོགས་ཁ་འདོན་ཁག་ཅིག
  author: ''
  volumes:
    dc94dbb0ad9b4a93a0c362ccf5e85262:
      image_group_id: I3MS69
      title: ''
      volume_number: 1
      total_pages: 328
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
